const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];

function injectShell(){
  const header = `<header class="site-header"><div class="container nav-wrap">
    <a class="logo" href="index.html" aria-label="SadhanamPickio home"><span>Sadhanam</span><strong>Pickio</strong><i class="fa-solid fa-hand-pointer"></i></a>
    <nav class="desktop-nav" aria-label="Primary navigation"><a href="index.html">Home</a><a href="trending.html">Trending</a><a href="categories.html">Categories</a><a href="deals.html">Deals</a><a href="reviews.html">Reviews</a><a href="articles.html">Articles</a></nav>
    <div class="nav-actions"><a class="icon-btn" href="search.html" aria-label="Search"><i class="fa-solid fa-magnifying-glass"></i></a><button class="icon-btn theme-toggle" aria-label="Toggle dark mode"><i class="fa-solid fa-moon"></i></button><button class="icon-btn menu-toggle" aria-label="Open menu" aria-expanded="false"><i class="fa-solid fa-bars"></i></button></div>
  </div><div class="mobile-nav"><a href="index.html">Home</a><a href="trending.html">Trending Products</a><a href="deals.html">Deals</a><a href="categories.html">Categories</a><a href="reviews.html">Reviews</a><a href="articles.html">Articles</a><a href="about.html">About</a><a href="contact.html">Contact</a></div></header>`;
  const footer = `<footer class="site-footer"><div class="container footer-grid"><div><a class="logo footer-logo" href="index.html"><span>Sadhanam</span><strong>Pickio</strong></a><p>Nalla Sadhanangal, Oru Pick-il.</p><p class="muted">Discover. Compare. Pick Better.</p></div><div><h3>Quick Links</h3><a href="index.html">Home</a><a href="trending.html">Trending</a><a href="deals.html">Deals</a><a href="categories.html">Categories</a><a href="reviews.html">Reviews</a></div><div><h3>Information</h3><a href="about.html">About</a><a href="contact.html">Contact</a><a href="privacy-policy.html">Privacy Policy</a><a href="terms.html">Terms</a><a href="affiliate-disclosure.html">Affiliate Disclosure</a></div><div><h3>Social</h3><a href="#" rel="nofollow">Instagram</a><a href="#" rel="nofollow">YouTube</a><a href="#" rel="nofollow">Facebook</a></div></div><div class="container footer-bottom"><span>© 2026 SadhanamPickio. All rights reserved.</span><span>Prices and availability may change.</span></div></footer>`;
  if($("#site-header")) $("#site-header").innerHTML=header;
  if($("#site-footer")) $("#site-footer").innerHTML=footer;
}
function initTheme(){
  const saved=localStorage.getItem("sp-theme"); if(saved==="dark") document.documentElement.dataset.theme="dark";
  const btn=$(".theme-toggle"); if(!btn) return;
  const update=()=>btn.innerHTML=document.documentElement.dataset.theme==="dark"?'<i class="fa-solid fa-sun"></i>':'<i class="fa-solid fa-moon"></i>';
  update(); btn.addEventListener("click",()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==="dark"?"":"dark"; localStorage.setItem("sp-theme",document.documentElement.dataset.theme||"light"); update();});
}
function initMenu(){const b=$(".menu-toggle"),m=$(".mobile-nav"); if(!b||!m)return;b.addEventListener("click",()=>{const open=m.classList.toggle("open");b.setAttribute("aria-expanded",open);b.innerHTML=open?'<i class="fa-solid fa-xmark"></i>':'<i class="fa-solid fa-bars"></i>';});}
function money(n){return "₹"+Number(n).toLocaleString("en-IN")}
function stars(r){return "★".repeat(Math.round(r))+"☆".repeat(5-Math.round(r))}
function productCard(p){
 return `<article class="product-card"><div class="product-media"><span class="badge">${p.status?.includes("trending")?"🔥 TRENDING":"PICK"}</span><button class="favorite-btn ${favorites().includes(p.id)?"saved":""}" data-fav="${p.id}" aria-label="Save ${p.name}"><i class="fa-${favorites().includes(p.id)?"solid":"regular"} fa-heart"></i></button><a href="product.html?id=${p.id}" class="product-visual" aria-label="${p.name}">${p.emoji}</a></div><div class="product-body"><span class="marketplace">${p.marketplace}</span><h3><a href="product.html?id=${p.id}">${p.name}</a></h3><p>${p.description}</p><div class="rating"><span>${stars(p.rating)}</span> <b>${p.rating}</b></div><div class="price-row"><strong>${money(p.price)}</strong>${p.oldPrice?`<del>${money(p.oldPrice)}</del>`:""}${p.discount?`<em>${p.discount}% OFF</em>`:""}</div><div class="card-actions"><a class="btn btn-primary btn-small" href="product.html?id=${p.id}">View Details</a><a class="btn btn-outline btn-small" href="${p.affiliateUrl}" target="_blank" rel="nofollow sponsored">Check Price</a></div></div></article>`;
}
function renderProducts(list,target){const el=typeof target==="string"?$(target):target;if(!el)return;el.innerHTML=list.length?list.map(productCard).join(""):`<div class="empty-state"><i class="fa-regular fa-face-frown"></i><h3>No products found</h3><p>Try a different search or filter.</p></div>`;bindFavorites();el.querySelectorAll(".product-card").forEach(c=>c.classList.add("reveal"))}
function favorites(){try{return JSON.parse(localStorage.getItem("sp-favorites")||"[]")}catch{return[]}}
function toggleFavorite(id){let f=favorites();f=f.includes(id)?f.filter(x=>x!==id):[...f,id];localStorage.setItem("sp-favorites",JSON.stringify(f))}
function bindFavorites(){$$("[data-fav]").forEach(b=>b.onclick=e=>{e.preventDefault();toggleFavorite(b.dataset.fav);const saved=favorites().includes(b.dataset.fav);b.classList.toggle("saved",saved);b.innerHTML=`<i class="fa-${saved?"solid":"regular"} fa-heart"></i>`})}
function saveViewed(id){let v=[];try{v=JSON.parse(localStorage.getItem("sp-viewed")||"[]")}catch{};v=[id,...v.filter(x=>x!==id)].slice(0,8);localStorage.setItem("sp-viewed",JSON.stringify(v))}
function renderCategories(target,large=false){const el=$(target);if(!el)return;el.innerHTML=categories.map(([name,icon,desc])=>`<a class="category-card ${large?"large":""}" href="category.html?category=${encodeURIComponent(name)}"><span>${icon}</span><div><h3>${name}</h3><p>${desc}</p></div><i class="fa-solid fa-arrow-right"></i></a>`).join("")}
function initHome(){renderProducts(products.filter(p=>p.status?.includes("trending")).slice(0,4),"#trending-grid");renderProducts([...products].sort((a,b)=>b.discount-a.discount).slice(0,4),"#deals-grid");renderCategories("#category-grid");renderProducts(products.filter(p=>p.price<=499).slice(0,6),"#under-499");renderProducts(products.filter(p=>p.price<=999).slice(0,6),"#under-999");renderProducts(products.filter(p=>p.status?.includes("popular")).slice(0,4),"#popular-grid");}
function initTrending(){const render=t=>renderProducts(t==="all"?products:products.filter(p=>p.status?.includes(t)||p.tags?.includes(t)),"#trending-page-grid");render("all");$$("[data-trend]").forEach(b=>b.onclick=()=>{$$("[data-trend]").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.trend)})}
function initDeals(){let current="all";const run=()=>{let l=[...products];if(current==="discount")l.sort((a,b)=>b.discount-a.discount);else if(current==="500")l=l.filter(p=>p.price<=500);else if(current==="999")l=l.filter(p=>p.price<=999);else if(current==="1999")l=l.filter(p=>p.price<=1999);const s=$("#deal-sort")?.value;if(s==="price")l.sort((a,b)=>a.price-b.price);if(s==="rating")l.sort((a,b)=>b.rating-a.rating);if(s==="discount")l.sort((a,b)=>b.discount-a.discount);renderProducts(l,"#deals-page-grid")};$$("[data-deal]").forEach(b=>b.onclick=()=>{$$("[data-deal]").forEach(x=>x.classList.remove("active"));b.classList.add("active");current=b.dataset.deal;run()});$("#deal-sort")?.addEventListener("change",run);run()}
function initArticles(kind="article"){const data=[["10 Useful Gadgets Under ₹999","Buying Guide","A practical demo guide for choosing affordable gadgets without chasing every trend."],["Best Everyday Audio Picks","Review","How to compare comfort, battery, sound and value when choosing everyday audio gear."],["5 Travel Gadgets Worth Considering","Travel","A simple checklist of compact accessories that can make trips easier."],["Product Comparison: What Actually Matters?","Comparison","Look beyond the headline specifications and compare what affects daily use."],["How SadhanamPickio Picks Products","Behind the Picks","Our demo curation framework: usefulness, value, clarity and transparency."]];const el=$(kind==="review"?"#review-grid":"#article-grid");if(!el)return;el.innerHTML=data.map((a,i)=>`<article class="article-card"><div class="article-art">${["💡","🎧","✈️","⚖️","🔎"][i]}</div><div><span class="tag">${a[1]}</span><h3>${a[0]}</h3><p>${a[2]}</p><a href="product.html?id=${products[i]?.id||products[0].id}">Read more →</a></div></article>`).join("")}
document.addEventListener("DOMContentLoaded",()=>{injectShell();initTheme();initMenu();const page=document.body.dataset.page;if(page==="home")initHome();if(page==="trending")initTrending();if(page==="deals")initDeals();if(page==="categories")renderCategories("#all-category-grid",true);if(page==="reviews")initArticles("review");if(page==="articles")initArticles();if(page==="category")initCategory();if(page==="search")initSearch();if(page==="product")saveViewed(new URLSearchParams(location.search).get("id"));if($("#newsletter-form"))$("#newsletter-form").addEventListener("submit",e=>{e.preventDefault();alert("Newsletter integration is not connected yet.");});if($("#contact-form"))$("#contact-form").addEventListener("submit",e=>{e.preventDefault();alert("Contact backend integration is not connected yet.");});});
function initCategory(){const q=new URLSearchParams(location.search);const initial=q.get("category")||"";const cats=$("#category-filter");cats.innerHTML='<option value="">All categories</option>'+categories.map(c=>`<option>${c[0]}</option>`).join("");if(initial)cats.value=initial;if(q.get("price"))$("#price-filter").value=q.get("price");const run=()=>{let l=[...products],cat=cats.value,price=$("#price-filter").value,r=$("#rating-filter").value,m=$("#market-filter").value,s=$("#sort-select").value;if(cat)l=l.filter(p=>p.category===cat);if(price==="500")l=l.filter(p=>p.price<=500);else if(price==="1000")l=l.filter(p=>p.price>500&&p.price<=1000);else if(price==="2000")l=l.filter(p=>p.price>1000&&p.price<=2000);else if(price==="5000")l=l.filter(p=>p.price>2000&&p.price<=5000);else if(price==="5000+")l=l.filter(p=>p.price>5000);if(r)l=l.filter(p=>p.rating>=+r);if(m)l=l.filter(p=>p.marketplace===m);if(s==="priceAsc")l.sort((a,b)=>a.price-b.price);if(s==="priceDesc")l.sort((a,b)=>b.price-a.price);if(s==="rating")l.sort((a,b)=>b.rating-a.rating);if(s==="discount")l.sort((a,b)=>b.discount-a.discount);if(s==="trending")l.sort((a,b)=>(b.status.includes("trending")?1:0)-(a.status.includes("trending")?1:0));$("#results-count").textContent=`${l.length} products found`;$("#category-title").textContent=cat||"All Products";renderProducts(l,"#category-products")};["category-filter","price-filter","rating-filter","market-filter","sort-select"].forEach(id=>$("#"+id)?.addEventListener("change",run));$("#clear-filters")?.addEventListener("click",()=>{cats.value="";$("#price-filter").value="";$("#rating-filter").value="";$("#market-filter").value="";$("#sort-select").value="popular";run()});run()}
