// DEMO DATA ONLY. Replace every demo value with researched product information before launch.
const products = [
 {id:"portable-mini-blender",name:"Portable Mini Blender",category:"Home Gadgets",price:799,oldPrice:1299,discount:38,rating:4.5,marketplace:"Amazon",emoji:"🥤",description:"Demo portable blender for travel and everyday use.",affiliateUrl:"#",tags:["trending","kitchen","travel","popular"],status:["trending","popular"],features:["Compact form","USB rechargeable","Travel friendly"],pros:["Portable","Simple to use"],cons:["Demo specification"],bestFor:"Travel and everyday convenience"},
 {id:"wireless-earbuds-lite",name:"Wireless Earbuds Lite",category:"Audio",price:999,oldPrice:1599,discount:38,rating:4.4,marketplace:"Flipkart",emoji:"🎧",description:"Demo wireless earbuds focused on everyday listening.",affiliateUrl:"#",tags:["audio","trending","earbuds"],status:["trending","rising"],features:["Wireless audio","Compact case","Touch controls"],pros:["Portable","Easy pairing"],cons:["Demo specification"],bestFor:"Everyday listening"},
 {id:"smartphone-stand",name:"Adjustable Smartphone Stand",category:"Mobile Accessories",price:299,oldPrice:499,discount:40,rating:4.6,marketplace:"Meesho",emoji:"📱",description:"Demo adjustable stand for desks and bedside tables.",affiliateUrl:"#",tags:["mobile","desk","budget","popular"],status:["popular"],features:["Adjustable angle","Foldable"],pros:["Affordable","Compact"],cons:["Demo specification"],bestFor:"Desk setups"},
 {id:"bike-phone-mount",name:"Universal Bike Phone Mount",category:"Bike Accessories",price:449,oldPrice:699,discount:36,rating:4.3,marketplace:"Amazon",emoji:"🏍️",description:"Demo handlebar phone mount concept for riders.",affiliateUrl:"#",tags:["bike","travel","rising"],status:["rising"],features:["Handlebar mount","Adjustable grip"],pros:["Convenient"],cons:["Demo specification"],bestFor:"Navigation while riding"},
 {id:"travel-organizer",name:"Compact Travel Organizer",category:"Travel Gadgets",price:399,oldPrice:599,discount:33,rating:4.5,marketplace:"Flipkart",emoji:"🎒",description:"Demo organizer for cables, chargers and small accessories.",affiliateUrl:"#",tags:["travel","organizer","hidden"],status:["hidden"],features:["Multiple compartments","Compact"],pros:["Keeps items organized"],cons:["Demo specification"],bestFor:"Travel"},
 {id:"led-desk-lamp",name:"USB LED Desk Lamp",category:"Home Gadgets",price:699,oldPrice:999,discount:30,rating:4.2,marketplace:"Amazon",emoji:"💡",description:"Demo compact desk lamp with adjustable positioning.",affiliateUrl:"#",tags:["home","desk","popular"],status:["popular"],features:["USB power","Adjustable head"],pros:["Desk friendly"],cons:["Demo specification"],bestFor:"Study and work desks"},
 {id:"gaming-mouse",name:"Ergonomic Gaming Mouse",category:"Gaming",price:899,oldPrice:1499,discount:40,rating:4.5,marketplace:"Flipkart",emoji:"🖱️",description:"Demo wired gaming mouse for desktop users.",affiliateUrl:"#",tags:["gaming","popular","trending"],status:["trending","popular"],features:["Ergonomic shape","Programmable buttons"],pros:["Comfort focused"],cons:["Demo specification"],bestFor:"Gaming and desktop use"},
 {id:"car-cable-organizer",name:"Car Cable Organizer",category:"Car Accessories",price:249,oldPrice:399,discount:38,rating:4.1,marketplace:"Meesho",emoji:"🚗",description:"Demo cable management accessory for vehicles.",affiliateUrl:"#",tags:["car","budget"],status:["hidden"],features:["Compact","Easy installation"],pros:["Low cost"],cons:["Demo specification"],bestFor:"Keeping car cables tidy"},
 {id:"power-bank-10000",name:"10,000mAh Power Bank",category:"Mobile Accessories",price:1299,oldPrice:1799,discount:28,rating:4.4,marketplace:"Amazon",emoji:"🔋",description:"Demo everyday power bank listing.",affiliateUrl:"#",tags:["mobile","travel","popular"],status:["popular"],features:["10,000mAh class","USB output"],pros:["Useful for travel"],cons:["Demo specification"],bestFor:"Daily backup power"},
 {id:"mini-tripod",name:"Flexible Mini Tripod",category:"Mobile Accessories",price:599,oldPrice:899,discount:33,rating:4.3,marketplace:"Flipkart",emoji:"📸",description:"Demo flexible tripod for phones and small cameras.",affiliateUrl:"#",tags:["creator","travel","rising"],status:["rising"],features:["Flexible legs","Phone compatible"],pros:["Portable"],cons:["Demo specification"],bestFor:"Content creators"},
 {id:"gaming-headset",name:"Entry Gaming Headset",category:"Gaming",price:1499,oldPrice:2299,discount:35,rating:4.2,marketplace:"Amazon",emoji:"🎮",description:"Demo over-ear gaming headset concept.",affiliateUrl:"#",tags:["gaming","audio"],status:["hidden"],features:["Over-ear design","Boom mic"],pros:["Gaming oriented"],cons:["Demo specification"],bestFor:"Casual gaming"},
 {id:"smart-watch-demo",name:"Everyday Smart Device",category:"Smart Devices",price:1999,oldPrice:2999,discount:33,rating:4.1,marketplace:"Flipkart",emoji:"⌚",description:"Demo wearable product placeholder.",affiliateUrl:"#",tags:["smart","popular"],status:["popular"],features:["Demo feature set"],pros:["Modern form"],cons:["Demo specification"],bestFor:"Everyday use"},
 {id:"travel-adapter",name:"Universal Travel Adapter",category:"Travel Gadgets",price:899,oldPrice:1299,discount:31,rating:4.5,marketplace:"Amazon",emoji:"🔌",description:"Demo universal travel adapter placeholder.",affiliateUrl:"#",tags:["travel","rising"],status:["rising"],features:["Multi-format concept"],pros:["Travel friendly"],cons:["Demo specification"],bestFor:"International travel"},
 {id:"laptop-stand",name:"Aluminium Laptop Stand",category:"Computer Accessories",price:1199,oldPrice:1799,discount:33,rating:4.6,marketplace:"Amazon",emoji:"💻",description:"Demo laptop stand for ergonomic desk setups.",affiliateUrl:"#",tags:["computer","desk","popular"],status:["popular"],features:["Elevated design","Foldable"],pros:["Desk friendly"],cons:["Demo specification"],bestFor:"Work and study"},
 {id:"usb-c-hub",name:"USB-C Multiport Hub",category:"Computer Accessories",price:1599,oldPrice:2199,discount:27,rating:4.3,marketplace:"Flipkart",emoji:"🔗",description:"Demo multiport hub placeholder.",affiliateUrl:"#",tags:["computer","usb","trending"],status:["trending"],features:["Multiple ports"],pros:["Connectivity"],cons:["Demo specification"],bestFor:"Laptop users"},
 {id:"car-cleaning-kit",name:"Compact Car Cleaning Kit",category:"Car Accessories",price:499,oldPrice:799,discount:38,rating:4.2,marketplace:"Meesho",emoji:"🧽",description:"Demo compact vehicle cleaning kit.",affiliateUrl:"#",tags:["car","budget","hidden"],status:["hidden"],features:["Compact storage"],pros:["Convenient"],cons:["Demo specification"],bestFor:"Basic car care"},
 {id:"wireless-keyboard",name:"Slim Wireless Keyboard",category:"Computer Accessories",price:1299,oldPrice:1899,discount:32,rating:4.4,marketplace:"Amazon",emoji:"⌨️",description:"Demo slim keyboard placeholder.",affiliateUrl:"#",tags:["computer","desk","popular"],status:["popular"],features:["Wireless","Slim"],pros:["Clean desk setup"],cons:["Demo specification"],bestFor:"Office and home work"},
 {id:"phone-camera-lens",name:"Clip-On Phone Lens Kit",category:"Mobile Accessories",price:349,oldPrice:599,discount:42,rating:4.0,marketplace:"Meesho",emoji:"🔭",description:"Demo phone camera accessory placeholder.",affiliateUrl:"#",tags:["mobile","creator","trending"],status:["trending"],features:["Clip-on design"],pros:["Low entry price"],cons:["Demo specification"],bestFor:"Casual mobile photography"}
];
const categories = [
 ["Mobile & Accessories","📱","Mobile accessories and useful phone add-ons."],["Audio","🎧","Earbuds, headphones and everyday audio."],["Gaming","🎮","Gaming accessories and desktop gear."],["Home Gadgets","🏠","Useful gadgets for everyday home life."],["Car Accessories","🚗","Practical accessories for your car."],["Bike Accessories","🏍️","Useful riding and bike accessories."],["Travel Gadgets","✈️","Compact products for trips and journeys."],["Computer Accessories","💻","Desk, laptop and connectivity accessories."],["Smart Devices","⌚","Wearables and smart everyday devices."],["Viral Products","🔥","Interesting products getting attention."]
];